## sample identifier
sampleid: "test"

##Kraken result file (stdout)
kraken: "testfiles/ebv_hpv.kout.tsv"

## Kraken Report (used to identify child taxids)
kreport: "testfiles/ebv_hpv.kreport.tsv"

## Path to fastq reads classified
r1: "testfiles/ebv_1000_hpv16_1000.R1.fq"

## Path to fastq reads classified
r2: "testfiles/ebv_1000_hpv16_1000.R2.fq"

## Taxid to extract (will include children)
taxid: 3050299

## A folder containing bwa-mem2 + minimap2 indexed microbial genomes
## Reads assigned to taxid X will be aligned to those reference genomes
refgenomes: "testfiles/refgenomes"

## Whole Genome Assembly Quast Stats
quast_est_ref_size: 1000
quast_min_contig: 50

## Should we annotate bacterial genomes that we assemble de novo?
run_assembly_annotation: false # We keep this false because we need
bakta_database: "testfiles/bakta_db"

## Path to BAKTA database for bacterial genome annotation
#### This database is a toy db for testing. Please install the full bakta database by running
#### `bakta_db download --output bakta_db` and change to that
#bakta_database: "testfiles/bakta_db"

## Run Remote Blast on subsample of 200 reads?
run_remote_blastn: false

## output directory
outdir: "micritesleuth"
